### ISSUE TITLE
Client generator fail

### ISSUE THREAD

**Issue by ksom** [api-platform/api-platform#1800]
**API Platform version(s) affected**: 2.6.1

**Description**  
When I run: `docker-compose exec pwa npx @api-platform/client-generator https://localhost . --generator next --resource greeting`

I have the following error stack trace 

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/152/lib/node_modules/@api-platform/client-generator/node_modules/highlight.js/deprecated.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! highlight.js@9.18.5 postinstall: `node deprecated.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the highlight.js@9.18.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-06T17_51_05_067Z-debug.log
Install for [ '@api-platform/client-generator@latest' ] failed with code 1
```

**How to reproduce**  
1: Install api-platform 2.6.1
2: run `docker-compose exec pwa npx @api-platform/client-generator https://localhost . --generator next --resource greeting`

**Comment by gusdecool** [comment]
use versioned package. Looks like latest version are unstable.

try this, add the api platform into your local dependencies

```
"dependencies": {
    "@api-platform/client-generator": "^0.6.0",
}
```

the run

```shell
npx generate-api-platform-client --generator typescript http://localhost src/
```

btw, you may want to use `http://` in case your certificate self signed.

**Comment by b2p-fred** [comment]
I met the same problem while trying to use the 0.6.0 version:
```
npx @api-platform/client-generator https://localhost . --generator next --resource greeting
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/215/lib/node_modules/@api-platform/client-generator/node_modules/highlight.js/deprecated.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! highlight.js@9.18.5 postinstall: `node deprecated.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the highlight.js@9.18.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-25T07_05_07_224Z-debug.log
Install for [ '@api-platform/client-generator@0.6.0' ] failed with code 1
```

**Comment by soyuka** [comment]
Closing per #2987 — this repository is becoming a CLI installer. The previous Docker/template distribution is being superseded by the installer + upstream [symfony-docker](https://github.com/dunglas/symfony-docker). If the issue still reproduces with the new setup, please open it on `dunglas/symfony-docker` (for Docker/Caddy/FrankenPHP issues) or `api-platform/core` (for framework issues).
