### ISSUE TITLE
unable to generate clients for api's contains "-" (dash/minus)

### ISSUE THREAD

**Issue by danysz** [api-platform/api-platform#2469]
**API Platform version(s) affected**: 3.0.10

**Description**  
I am trying to generate only the client for an API which is OpenAPI v3 written using loopback.io 4 (latest release)
The API is working and is in use by different clients.
The generation fail on resources with names counting "dash" ("-")
The file which is not created is in the "types" directory.

**How to reproduce**  
Try to generate a client for Nuxt on endpoint which name is "end-point" (or anything with a "minus" in it)

**Possible Solution**  
Just to make it work.

**Additional Context**  
SyntaxError: Unexpected token, expected "," (2:18)
  1 | import { defineStore } from "pinia";
> 2 | import { Activity-type } from "~~/types/activity-type";
    |                  ^
  3 | import type { SubmissionErrors } from "~~/types/error";
  4 | import { CreateItemData } from "~~/types/api";
  5 |
    at p (/Users/danysz/.config/yarn/global/node_modules/prettier/parser-babel.js:22:1054)
    at d (/Users/danysz/.config/yarn/global/node_modules/prettier/parser-babel.js:22:1287)
    at Object.parse (/Users/danysz/.config/yarn/global/node_modules/prettier/parser-babel.js:29:54501)
    at Object.parse (/Users/danysz/.config/yarn/global/node_modules/prettier/index.js:7515:23)
    at coreFormat (/Users/danysz/.config/yarn/global/node_modules/prettier/index.js:8829:18)
    at formatWithCursor2 (/Users/danysz/.config/yarn/global/node_modules/prettier/index.js:9021:18)
    at /Users/danysz/.config/yarn/global/node_modules/prettier/index.js:38183:12
    at Object.format (/Users/danysz/.config/yarn/global/node_modules/prettier/index.js:38197:12)
    at NuxtGenerator.createFile (file:///Users/danysz/.config/yarn/global/node_modules/@api-platform/create-client/lib/generators/BaseGenerator.js:76:28)
    at NuxtGenerator.createFileFromPattern (file:///Users/danysz/.config/yarn/global/node_modules/@api-platform/create-client/lib/generators/BaseGenerator.js:57:12) {
  loc: { start: { line: 2, column: 18 } },

**Comment by soyuka** [comment]
Closing as stale per #2987 (no activity since 2023-07-04). This repository is transitioning to a CLI installer. If this still reproduces against a current release of API Platform, please open a new issue on `api-platform/core` with a minimal reproduction.
