### ISSUE TITLE
Docker: Install api-platform/laravel via Composer without database connection

### ISSUE THREAD

**Issue by cay89** [api-platform/api-platform#2772]
**API Platform version(s) affected**: 4.0.2

**Description**  

I have an existing, containerized Laravel project. My app container doesn't contain Composer, because I use Composer separately via the [official Composer image](https://hub.docker.com/_/composer). I've installed the api-platform/laravel package via the following command:

```bash
docker run --rm -v $(pwd):/app composer require api-platform/laravel
```

It works fine. Then, I've tried to test API Platform so I've added an attribute to my User model:

```php
#[ApiResource(operations: [new Get(), new GetCollection()])]
class User extends AbstractModel implements
    AuthenticatableContract,
    AuthorizableContract
{
  // ...
}
```

The problem starts when after that, I run the `composer install` command again:

```bash
docker run --rm -v $(pwd):/app composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Database\QueryException 

  could not find driver (Connection: mariadb, SQL: select column_name as `name`, data_type as `type_name`, column_type as `type`, collation_name as `collation`, is_nullable as `nullable`, column_default as `default`, column_comment as `comment`, generation_expression as `expression`, extra as `extra` from information_schema.columns where table_schema = 'admin_api' and table_name = 'users' order by ordinal_position asc)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕ 
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

  1   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(ApiPlatform\Laravel\ApiPlatformProvider), "ApiPlatform\Laravel\ApiPlatformProvider")
      +46 vendor frames 

  48  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(ApiPlatform\Laravel\ApiPlatformProvider), "ApiPlatform\Laravel\ApiPlatformProvider")
```

In this case, the package wants to establish a driver and the database connection during installation, but obviously cannot, because there is no such thing in this Composer's container.

Why does it want to connect to the database? How could it be solved so that it doesn't do it? I don't think installing a package would justify the existence of a database connection.

**How to reproduce**  
1. clone a laravel project
2. add the `api-platform/laravel` as dependency
3. add an attribute to User model like above
4. run the `composer install` command in the official Composer container
`docker run --rm -v $(pwd):/app composer install`

**Comment by cay89** [comment]
Here is the full stacktrace of the error:

```
[2024-10-03 05:17:39] local.ERROR: could not find driver (Connection: mariadb, SQL: select column_name as `name`, data_type as `type_name`, column_type as `type`, collation_name as `collation`, is_nullable as `nullable`, column_default as `default`, column_comment as `comment`, generation_expression as `expression`, extra as `extra` from information_schema.columns where table_schema = 'admin_api' and table_name = 'users' order by ordinal_position asc) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (Connection: mariadb, SQL: select column_name as `name`, data_type as `type_name`, column_type as `type`, collation_name as `collation`, is_nullable as `nullable`, column_default as `default`, column_comment as `comment`, generation_expression as `expression`, extra as `extra` from information_schema.columns where table_schema = 'admin_api' and table_name = 'users' order by ordinal_position asc) at /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(779): Illuminate\\Database\\Connection->runQueryCallback('select column_n...', Array, Object(Closure))
#1 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\\Database\\Connection->run('select column_n...', Array, Object(Closure))
#2 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(385): Illuminate\\Database\\Connection->select('select column_n...', Array, false)
#3 /app/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(71): Illuminate\\Database\\Connection->selectFromWriteConnection('select column_n...')
#4 /app/vendor/api-platform/laravel/Eloquent/Metadata/ModelMetadata.php(68): Illuminate\\Database\\Schema\\MySqlBuilder->getColumns('users')
#5 /app/vendor/api-platform/laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyNameCollectionMetadataFactory.php(55): ApiPlatform\\Laravel\\Eloquent\\Metadata\\ModelMetadata->getAttributes(Object(App\\Models\\User))
#6 /app/vendor/api-platform/metadata/Property/Factory/ConcernsPropertyNameCollectionMetadataFactory.php(38): ApiPlatform\\Laravel\\Eloquent\\Metadata\\Factory\\Property\\EloquentPropertyNameCollectionMetadataFactory->create('App\\\\Models\\\\User', Array)
#7 /app/vendor/api-platform/metadata/Property/Factory/ClassLevelAttributePropertyNameCollectionFactory.php(31): ApiPlatform\\Metadata\\Property\\Factory\\ConcernsPropertyNameCollectionMetadataFactory->create('App\\\\Models\\\\User', Array)
#8 /app/vendor/api-platform/laravel/Metadata/CachePropertyNameCollectionMetadataFactory.php(33): ApiPlatform\\Metadata\\Property\\Factory\\ClassLevelAttributePropertyNameCollectionFactory->create('App\\\\Models\\\\User', Array)
#9 /app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(471): ApiPlatform\\Laravel\\Metadata\\CachePropertyNameCollectionMetadataFactory->ApiPlatform\\Laravel\\Metadata\\{closure}()
#10 /app/vendor/api-platform/laravel/Metadata/CachePropertyNameCollectionMetadataFactory.php(32): Illuminate\\Cache\\Repository->rememberForever('929f6a9ba42c75e...', Object(Closure))
#11 /app/vendor/api-platform/metadata/Resource/Factory/LinkFactory.php(145): ApiPlatform\\Laravel\\Metadata\\CachePropertyNameCollectionMetadataFactory->create('App\\\\Models\\\\User')
#12 /app/vendor/api-platform/metadata/Resource/Factory/LinkFactory.php(54): ApiPlatform\\Metadata\\Resource\\Factory\\LinkFactory->getIdentifiersFromResourceClass('App\\\\Models\\\\User')
#13 /app/vendor/api-platform/metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php(137): ApiPlatform\\Metadata\\Resource\\Factory\\LinkFactory->createLinksFromIdentifiers(Object(ApiPlatform\\Metadata\\ApiResource))
#14 /app/vendor/api-platform/metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php(48): ApiPlatform\\Metadata\\Resource\\Factory\\UriTemplateResourceMetadataCollectionFactory->configureUriVariables(Object(ApiPlatform\\Metadata\\ApiResource))
#15 /app/vendor/api-platform/metadata/Resource/Factory/LinkResourceMetadataCollectionFactory.php(37): ApiPlatform\\Metadata\\Resource\\Factory\\UriTemplateResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#16 /app/vendor/api-platform/metadata/Resource/Factory/OperationNameResourceMetadataCollectionFactory.php(39): ApiPlatform\\Metadata\\Resource\\Factory\\LinkResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#17 /app/vendor/api-platform/metadata/Resource/Factory/PhpDocResourceMetadataCollectionFactory.php(74): ApiPlatform\\Metadata\\Resource\\Factory\\OperationNameResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#18 /app/vendor/api-platform/metadata/Resource/Factory/InputOutputResourceMetadataCollectionFactory.php(37): ApiPlatform\\Metadata\\Resource\\Factory\\PhpDocResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#19 /app/vendor/api-platform/metadata/Resource/Factory/FormatsResourceMetadataCollectionFactory.php(53): ApiPlatform\\Metadata\\Resource\\Factory\\InputOutputResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#20 /app/vendor/api-platform/metadata/Resource/Factory/FiltersResourceMetadataCollectionFactory.php(41): ApiPlatform\\Metadata\\Resource\\Factory\\FormatsResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#21 /app/vendor/api-platform/metadata/Resource/Factory/AlternateUriResourceMetadataCollectionFactory.php(34): ApiPlatform\\Metadata\\Resource\\Factory\\FiltersResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#22 /app/vendor/api-platform/metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php(48): ApiPlatform\\Metadata\\Resource\\Factory\\AlternateUriResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#23 /app/vendor/api-platform/laravel/Metadata/ParameterValidationResourceMetadataCollectionFactory.php(33): ApiPlatform\\Metadata\\Resource\\Factory\\ParameterResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#24 /app/vendor/api-platform/laravel/Eloquent/Metadata/Factory/Resource/EloquentResourceCollectionMetadataFactory.php(54): ApiPlatform\\Laravel\\Metadata\\ParameterValidationResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#25 /app/vendor/api-platform/laravel/Metadata/CacheResourceCollectionMetadataFactory.php(31): ApiPlatform\\Laravel\\Eloquent\\Metadata\\Factory\\Resource\\EloquentResourceCollectionMetadataFactory->create('App\\\\Models\\\\User')
#26 /app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(471): ApiPlatform\\Laravel\\Metadata\\CacheResourceCollectionMetadataFactory->ApiPlatform\\Laravel\\Metadata\\{closure}()
#27 /app/vendor/api-platform/laravel/Metadata/CacheResourceCollectionMetadataFactory.php(30): Illuminate\\Cache\\Repository->rememberForever('App\\\\Models\\\\User', Object(Closure))
#28 /app/vendor/api-platform/laravel/ApiPlatformProvider.php(1240): ApiPlatform\\Laravel\\Metadata\\CacheResourceCollectionMetadataFactory->create('App\\\\Models\\\\User')
#29 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): ApiPlatform\\Laravel\\ApiPlatformProvider->boot(Object(ApiPlatform\\Metadata\\Resource\\Factory\\ConcernsResourceNameCollectionFactory), Object(ApiPlatform\\Laravel\\Metadata\\CacheResourceCollectionMetadataFactory), Object(Illuminate\\Routing\\Router))
#30 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#31 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#32 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#33 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#34 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1119): Illuminate\\Container\\Container->call(Array)
#35 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1100): Illuminate\\Foundation\\Application->bootProvider(Object(ApiPlatform\\Laravel\\ApiPlatformProvider))
#36 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(ApiPlatform\\Laravel\\ApiPlatformProvider), 'ApiPlatform\\\\Lar...')
#37 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1099): array_walk(Array, Object(Closure))
#38 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#39 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#40 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(473): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#41 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#42 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 /app/artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#44 {main}

[previous exception] [object] (PDOException(code: 0): could not find driver at /app/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:66)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(66): PDO->__construct('mysql:host=olm5...', 'root', Object(SensitiveParameterValue), Array)
#1 /app/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=olm5...', 'root', 'rNMdXicBhlDagUv...', Array)
#2 /app/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=olm5...', Array, Array)
#3 /app/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(185): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1231): call_user_func(Object(Closure))
#6 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(512): Illuminate\\Database\\Connection->getPdo()
#7 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\\Database\\Connection->getPdoForSelect(false)
#8 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(812): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select column_n...', Array)
#9 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(779): Illuminate\\Database\\Connection->runQueryCallback('select column_n...', Array, Object(Closure))
#10 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\\Database\\Connection->run('select column_n...', Array, Object(Closure))
#11 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(385): Illuminate\\Database\\Connection->select('select column_n...', Array, false)
#12 /app/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(71): Illuminate\\Database\\Connection->selectFromWriteConnection('select column_n...')
#13 /app/vendor/api-platform/laravel/Eloquent/Metadata/ModelMetadata.php(68): Illuminate\\Database\\Schema\\MySqlBuilder->getColumns('users')
#14 /app/vendor/api-platform/laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyNameCollectionMetadataFactory.php(55): ApiPlatform\\Laravel\\Eloquent\\Metadata\\ModelMetadata->getAttributes(Object(App\\Models\\User))
#15 /app/vendor/api-platform/metadata/Property/Factory/ConcernsPropertyNameCollectionMetadataFactory.php(38): ApiPlatform\\Laravel\\Eloquent\\Metadata\\Factory\\Property\\EloquentPropertyNameCollectionMetadataFactory->create('App\\\\Models\\\\User', Array)
#16 /app/vendor/api-platform/metadata/Property/Factory/ClassLevelAttributePropertyNameCollectionFactory.php(31): ApiPlatform\\Metadata\\Property\\Factory\\ConcernsPropertyNameCollectionMetadataFactory->create('App\\\\Models\\\\User', Array)
#17 /app/vendor/api-platform/laravel/Metadata/CachePropertyNameCollectionMetadataFactory.php(33): ApiPlatform\\Metadata\\Property\\Factory\\ClassLevelAttributePropertyNameCollectionFactory->create('App\\\\Models\\\\User', Array)
#18 /app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(471): ApiPlatform\\Laravel\\Metadata\\CachePropertyNameCollectionMetadataFactory->ApiPlatform\\Laravel\\Metadata\\{closure}()
#19 /app/vendor/api-platform/laravel/Metadata/CachePropertyNameCollectionMetadataFactory.php(32): Illuminate\\Cache\\Repository->rememberForever('929f6a9ba42c75e...', Object(Closure))
#20 /app/vendor/api-platform/metadata/Resource/Factory/LinkFactory.php(145): ApiPlatform\\Laravel\\Metadata\\CachePropertyNameCollectionMetadataFactory->create('App\\\\Models\\\\User')
#21 /app/vendor/api-platform/metadata/Resource/Factory/LinkFactory.php(54): ApiPlatform\\Metadata\\Resource\\Factory\\LinkFactory->getIdentifiersFromResourceClass('App\\\\Models\\\\User')
#22 /app/vendor/api-platform/metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php(137): ApiPlatform\\Metadata\\Resource\\Factory\\LinkFactory->createLinksFromIdentifiers(Object(ApiPlatform\\Metadata\\ApiResource))
#23 /app/vendor/api-platform/metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php(48): ApiPlatform\\Metadata\\Resource\\Factory\\UriTemplateResourceMetadataCollectionFactory->configureUriVariables(Object(ApiPlatform\\Metadata\\ApiResource))
#24 /app/vendor/api-platform/metadata/Resource/Factory/LinkResourceMetadataCollectionFactory.php(37): ApiPlatform\\Metadata\\Resource\\Factory\\UriTemplateResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#25 /app/vendor/api-platform/metadata/Resource/Factory/OperationNameResourceMetadataCollectionFactory.php(39): ApiPlatform\\Metadata\\Resource\\Factory\\LinkResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#26 /app/vendor/api-platform/metadata/Resource/Factory/PhpDocResourceMetadataCollectionFactory.php(74): ApiPlatform\\Metadata\\Resource\\Factory\\OperationNameResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#27 /app/vendor/api-platform/metadata/Resource/Factory/InputOutputResourceMetadataCollectionFactory.php(37): ApiPlatform\\Metadata\\Resource\\Factory\\PhpDocResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#28 /app/vendor/api-platform/metadata/Resource/Factory/FormatsResourceMetadataCollectionFactory.php(53): ApiPlatform\\Metadata\\Resource\\Factory\\InputOutputResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#29 /app/vendor/api-platform/metadata/Resource/Factory/FiltersResourceMetadataCollectionFactory.php(41): ApiPlatform\\Metadata\\Resource\\Factory\\FormatsResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#30 /app/vendor/api-platform/metadata/Resource/Factory/AlternateUriResourceMetadataCollectionFactory.php(34): ApiPlatform\\Metadata\\Resource\\Factory\\FiltersResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#31 /app/vendor/api-platform/metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php(48): ApiPlatform\\Metadata\\Resource\\Factory\\AlternateUriResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#32 /app/vendor/api-platform/laravel/Metadata/ParameterValidationResourceMetadataCollectionFactory.php(33): ApiPlatform\\Metadata\\Resource\\Factory\\ParameterResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#33 /app/vendor/api-platform/laravel/Eloquent/Metadata/Factory/Resource/EloquentResourceCollectionMetadataFactory.php(54): ApiPlatform\\Laravel\\Metadata\\ParameterValidationResourceMetadataCollectionFactory->create('App\\\\Models\\\\User')
#34 /app/vendor/api-platform/laravel/Metadata/CacheResourceCollectionMetadataFactory.php(31): ApiPlatform\\Laravel\\Eloquent\\Metadata\\Factory\\Resource\\EloquentResourceCollectionMetadataFactory->create('App\\\\Models\\\\User')
#35 /app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(471): ApiPlatform\\Laravel\\Metadata\\CacheResourceCollectionMetadataFactory->ApiPlatform\\Laravel\\Metadata\\{closure}()
#36 /app/vendor/api-platform/laravel/Metadata/CacheResourceCollectionMetadataFactory.php(30): Illuminate\\Cache\\Repository->rememberForever('App\\\\Models\\\\User', Object(Closure))
#37 /app/vendor/api-platform/laravel/ApiPlatformProvider.php(1240): ApiPlatform\\Laravel\\Metadata\\CacheResourceCollectionMetadataFactory->create('App\\\\Models\\\\User')
#38 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): ApiPlatform\\Laravel\\ApiPlatformProvider->boot(Object(ApiPlatform\\Metadata\\Resource\\Factory\\ConcernsResourceNameCollectionFactory), Object(ApiPlatform\\Laravel\\Metadata\\CacheResourceCollectionMetadataFactory), Object(Illuminate\\Routing\\Router))
#39 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#40 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#41 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#42 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#43 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1119): Illuminate\\Container\\Container->call(Array)
#44 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1100): Illuminate\\Foundation\\Application->bootProvider(Object(ApiPlatform\\Laravel\\ApiPlatformProvider))
#45 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(ApiPlatform\\Laravel\\ApiPlatformProvider), 'ApiPlatform\\\\Lar...')
#46 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1099): array_walk(Array, Object(Closure))
#47 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#48 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#49 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(473): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#50 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#51 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#52 /app/artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#53 {main}
"} 
```

**Comment by soyuka** [comment]
We need the database to be up to read eloquent's metadata.

**Comment by cay89** [comment]
So, the problem is with the default composer script that runs `package:discovery`, which registers the `ApiPlatformProvider`, but that requires a database connection at some point. 

![image](https://github.com/user-attachments/assets/921134dd-9d6e-4277-94db-7b671f9fbb7b)

The solution might be to modify `composer.json` to not run `package:discovery` automatically, but to run it manually later (in my app container) when the database connection is live.

**Comment by dunglas** [comment]
This could be not to add documentation for this. Docker is a very common setup these days.

**Comment by cay89** [comment]
This also causes problems when I run Larastan on the project in a CI/CD pipeline. Obviously, there won't be a database available, but Larastan [boots](https://github.com/larastan/larastan/blob/2.x/bootstrap.php) the Laravel app and then crashes with an error. What is the suggested solution for this?

**Comment by dunglas** [comment]
@cay89 use SQLite (or a real DB server but it will be slower) and run the migrations before starting Larastan, so the app will boot properly.

**Comment by floodedcodeboy** [comment]
Sorry, I feel like closing this issue without any sort of 'real' solution is a total cop out. 

Please at least add this to the documentation, it's a huge 'gotcha' and ultimately forces developers to re-design their existing setup to accommodate this package. 

Additionally a Docker example with laravel (not just a symfony example) would be a real treat, I can dream right?

**Comment by dunglas** [comment]
I discussed this issue with @soyuka at SymfonyCon.

Maybe could we provide a dev command to generate a file containing metadata computed using the active DB connection.
Users could then add this file to their git repository, or at least to the Docker image to allow building/booting the app without a DB connection.

**Comment by floodedcodeboy** [comment]
@dunglas I appreciate the quick response. I'm relieved to hear that its been on your mind. 

Your approach sounds straight forward, and maintainable enough to allow for docker images to be built without interfering too much with typical workflows.

**Comment by dunglas** [comment]
In the meantime, as a workaround, using SQLite instead of MySQL/Postgres at build time should work.

**Comment by floodedcodeboy** [comment]
@dunglas thanks again for the SQLite workaround.

I've also noticed that SQLite is used by `api-platform` regardless of the application settings when there is no running database. 

In my case I've setup redis for the cache, however when I build the docker container, of course neither of Redis/MySQL/Postgres services are available.
